### ISSUE TITLE
[Chat demo] Web version doesn't scroll at all in Firefox

### ISSUE THREAD

**Issue by cblp** [gritzko/swarm#100]
Looks this
![_028](https://user-images.githubusercontent.com/63495/38823169-58777c2a-41ae-11e8-9539-8de03997bd58.png)

And has no means to scroll to fresh messages.

**Comment by cblp** [comment]
@olebedev

**Comment by olebedev** [comment]
@cblp, let me guess, is this firefox? The chat is not working in firefox.

**Comment by cblp** [comment]
Ok, I reworded the bug's title.

**Comment by olebedev** [comment]
This is how https://github.com/necolas/react-native-web and https://github.com/FaridSafi/react-native-gifted-chat work together.

**Comment by cblp** [comment]
This is not a solution to the problem. Why did you close it?
