### ISSUE TITLE
Protobuf or similar smaller encoding?

### ISSUE THREAD

**Issue by Gregoor** [gritzko/swarm#21]
I really like your approach of solving one problem at a time (the full stack of isomorphs like Meteor is atm overblown imo). Especially since there are already great complementary libs like React for rendering.

Anyway, on topic: I looked at your demo app and saw that the traffic is sent in plain and I though, why not add protobuf to the mix? The gains are typically smaller messages (in the case of my websocket app, it was about 50% smaller) and faster encoding. If that is something you are interested in, I would work in my spare time on a pull request, which you can check out and see if you like it ;)

Thanks for the effort! :+1:

**Comment by gritzko** [comment]
nice bench http://jsperf.com/json-vs-protobuf
