### ISSUE TITLE
Spec object has `index` state which causes calls to be non-idempotent

### ISSUE THREAD

**Issue by rocketraman** [gritzko/swarm#53]
The Spec object has an internal `index` used for parsing which causes calls to be non-idempotent. For example:

```javascript
var someSpec = ...
console.log(spec.token('!'))
// prints Object {quant: "!", body: "2QXIl03+A0017r~0", bare: "2QXIl03", ext: "A0017r~0"}
console.log(spec.token('!'))
// prints undefined
someSpec.index = 0
console.log(spec.token('!'))
// prints Object {quant: "!", body: "2QXIl03+A0017r~0", bare: "2QXIl03", ext: "A0017r~0"}
```

Presumably `index` should be reset with Spec at the beginning of each parse method?

**Comment by gritzko** [comment]
Practically, index is not used anymore.
Removed it in 461dbb364f8a87f3e27e120259aebea1736508a0
Thanks.
