### ISSUE TITLE
Travel in time?

### ISSUE THREAD

**Issue by coodoo** [gritzko/swarm#66]
Since swarm is op-based CRDT, is it possible to implement travel-in-time kind of feature, say let user sees an very old version of the content by clicking on different dates?

**Comment by gritzko** [comment]
That is perfectly possible, at least the server-side storage has the full op history.
The question is who and when will implement that :)
Currently, I am focused on pushing the release out :|

**Comment by coodoo** [comment]
That sounds great, and good job on the v4 work, very expecting to see it's official release (and please squeeze in the time travel capability please :)
