### ISSUE TITLE
Libev development files not found

### ISSUE THREAD

**Issue by anton-putau** [gritzko/swarm#69]
Tried to built project with cmake on ubuntu 15.04 - get next error -

cmake .

header: ev++.h, arguments: libev ==> /usr/include
library: ev, arguments: libev ==> /usr/lib/x86_64-linux-gnu/libev.so
CMake Error at cmake/locate_library.cmake:14 (MESSAGE):
  libev development files are required to build.
Call Stack (most recent call first):
  CMakeLists.txt:13 (locate_library)

I have instaled libev-dev package, what else I need?
Thanks.

**Comment by gritzko** [comment]
What do you mean?
Swarm.js is a node.js project.
