### ISSUE TITLE
Is crdt really a good fit for collaborative text editing?

### ISSUE THREAD

**Issue by coodoo** [gritzko/swarm#74]
Been playing with various CRDT solutions to implement collaborative text editing which is real-time and offline-ready and I started to wonder since CRDT tends to be memory and disk storage heavy, will there eventually be performance issue after a long editing session (meaning oplog piling up, long syncing and replay time...etc)? Thanks!

**Comment by gritzko** [comment]
It is a perfect fit. All those efficiency issues are solvable.
A sophisticated implementation does not need the entire op log, compresses its metadata, etc.
Unfortunately, I am not aware of any *open-source* implementation that is sophisticated enough.
I may produce one eventually.

**Comment by coodoo** [comment]
Very looking forward to see such a sophisticated implementation, which will definitely be a killer demo!
