### ISSUE TITLE
Examples use SwarmJs version 1

### ISSUE THREAD

**Issue by wss-world** [gritzko/swarm#79]
Hi, I want to try to use Svarm.js. You can show an example of using the current version SwarmJs. 
I've seen your usage examples, but they are all for version 0.3.
Help with examples!
Thank you)

**Comment by gritzko** [comment]
Hi!

At the moment, the thing is rough on the edges and most docs are outdated, sorry.
You may track the progress of https://github.com/olebedev/swarm-mice-example
There are some examples in test/ folders too.
