### ISSUE TITLE
Tests don't pass?

### ISSUE THREAD

**Issue by slightlyoff** [gritzko/swarm#85]
Pulling a copy of the repo, I can't get tests to pass on either stable or unstable node. It looks like `swarm-client` and `swarm-stamp` have been removed from the repo (but not the `Makefile` or various module deps).

Would love to pitch in, but wondering if there's a stable starting point to work from.

Thanks.

**Comment by gritzko** [comment]
Status report:

* swarm-protocol: matches the spec, tests are OK
* swarm-bat: a testing tool, OK
* swarm-syncable: generic client code, only OpStream works OK, all data types need lots of attention
* swarm-peer: generic server/peer code, matches the spec, tests OK
* swarm-cli: CLI client, in progress
* swarm-server: CLI server, passes basic protocol tests

At this point, I am updating the client (-syncable, -cli) to pass protocol tests.
Then, I will have some time to add more types, I believe.

**Comment by gritzko** [comment]
This is the current list of packages in their order of dependence: `swarm-bat swarm-protocol swarm-syncable swarm-cli swarm-peer swarm-server swarm-browser swarm-gw`
https://github.com/gritzko/swarm/blob/master/scripts/add-links.sh#L4

`swarm-browser` is an in-browser client (WebStorage, WebSocket). That one is not up to date.

**Comment by slightlyoff** [comment]
Looking good now. Thanks!
